//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keithley26xx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keithley26xx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset()
        ///
        ///result_a = nil
        ///
        ///currentNAvg_smu_a = smua.measure.count
        ///currentNPLC_smu_a = smua.measure.nplc
        ///currentDelay_smu_a = smua.measure.delay
        ///
        ///currentCurrentLimit_smu_a = smua.source.limiti
        ///currentVoltageLimit_smu_a = smua.source.limitv
        ///currentOutputFunc_smu_a = smua.source.func
        ///
        ///currentMeasureCurrent_smua_AutorangeState = smua.measure.autorangei
        ///currentMeasureVoltage_smua_AutorangeState = smua.measure.autorangev
        ///
        ///currentMeasureFunction_smua = display.smua.measure.func
        ///
        ///function SetVoltage_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceFunctionsChannelA {
            get {
                return ResourceManager.GetString("DeviceFunctionsChannelA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset()
        ///
        ///result_b = nil
        ///
        ///currentNAvg_smu_b = smub.measure.count
        ///currentNPLC_smu_b = smub.measure.nplc
        ///currentDelay_smu_b = smub.measure.delay
        ///
        ///currentCurrentLimit_smu_b = smub.source.limiti
        ///currentVoltageLimit_smu_b = smub.source.limitv
        ///currentOutputFunc_smu_b = smub.source.func
        ///
        ///currentMeasureCurrent_smub_AutorangeState = smub.measure.autorangei
        ///currentMeasureVoltage_smub_AutorangeState = smub.measure.autorangev
        ///
        ///currentMeasureFunction_smub = display.smub.measure.func
        ///
        ///function SetVoltage_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceFunctionsChannelB {
            get {
                return ResourceManager.GetString("DeviceFunctionsChannelB", resourceCulture);
            }
        }
    }
}
